### ISSUE TITLE
loading data error

### ISSUE THREAD

**Issue by xchuwenbo** [Ian09/SupervisedDeepDocNADE#1]
I got an error when generating labeled data.
Here are the details of the error. Could you please take a look? @Ian09 

python gen_dataset_labeled.py
Loaded sparse matrix from /home/wenbo/mfs/data/flickr/text/text_all_2000_labelled.npz of shape (25000, 2000)
Traceback (most recent call last):
  File "gen_dataset_labeled.py", line 137, in <module>
    load('/home/wenbo/mfs/data/flickr', '/home/wenbo/mfs/data/flickr', 1)
  File "gen_dataset_labeled.py", line 117, in load
    trainset_matrix_global_features = train_global_features / std_global_features_unlab[:, np.newaxis]
ValueError: operands could not be broadcast together with shapes (10000,1857) (1857,1)

**Comment by Ian09** [comment]
sorry for the late reply. 
please change std_global_features_unlab[:, np.newaxis] to std_global_features_unlab[ np.newaxis, : ]
I am not sure whether I make a bug when I release the code. But this line is to have a unit std.
